# This workflow pulls recent blog posts
# and inserts into README.md
name: RSS autofetch
on:
  schedule:
  # Run every 6 hours
  - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://robdy.io/rss.xml'
          file: 'README.md'
          format: '- ${monthshort} ${02day} 📰 [${title}](${url})'
      - uses: sarisia/actions-commit@master
        with:
          message: 'Update blog posts'
